#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    List of terms manually created in https://github.com/softwaresaved/ref_case_studies_investigation_2014
"""


SEARCH_TERM_LIST = [
    'algorithm',
    'big data',
    'beautifulsoup',
    'code',
    'computation',
    'computational',
    'computed',
    'computer',
    'data analysis',
    'data base',
    'database',
    'excel',
    'fortran',
    'geographic information science',
    'geographic information systems',
    'gis',
    'git',
    'github',
    'graphics',
    'high performance computing',
    'hpc',
    'imagej',
    'implemented in',
    'in silico',
    'matlab',
    'matplotlib',
    'numpy',
    'nvivo',
    'open source',
    'open-source',
    'pipeline',
    'python',
    'quantitative',
    'regression',
    'r language',
    'in r',
    'scrapy',
    'scipy',
    'simulated',
    'simulation',
    'software',
    'spss',
    'sqlalchemy',
    'stata',
    'statistical'
    'supercomputing',
    'visualisation',
    'visualization',
    'Rcpp',
    'ggplot2',
    'plyr',
    'stringr',
    'reshape2',
    'RColorBrewer',
    'workflow',
    'wxpython'
]
