## General

1. Need to find a proper ***classifier*** for "software jobs". 
   I think the current classifier is next to useless.
1. Want identify and separate salaries that are on an hourly rate.
1. Have a world map of the distribution of jobs?
1. Look at subject by location.
1. Generate linear equation of cunulative downloads and overplot 
   (at the moment this does not appear to be working)
1. Move the geocoding for generation of a map to a subroutine.
1. Rationalise the salary R code - fair bit of replication used to generate 
   the different plots.
1. Can we add a linear fit to cumulative downloads per day (time series).
1. Rationalise this document so there is more joined up use of the R fragments. 
   Currently data is being recreated a number of times. There are also hidden 
   dependencies - modification of code upstream can mess up analysis downstream.
1. Look at salaries for specific programming jobs where these can be identified.
1. Look at the reference id for jobs. It appears that institutions are reposting
   jobs. This is done within the closing date for the job in the institution and
   it may well be a ploy to generate more applicants for their jobs. This needs
   further investigation.

